language: go

sudo: required

addons:
  apt:
    packages:
      - redis-server
      - lynx
      - jq

go:
  - "1.10"
      
before_script:
  - sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
  - pushd packer
  - if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
  - popd
  - bash scripts/install_consul.sh
  - bash scripts/install_vault.sh
       
script:
  - source ./var.env
  - export REDIS_MASTER_IP=127.0.0.1
  - export REDIS_MASTER_PASSWORD=""
  - export LISTENER_COUNT=1
  - consul kv put "development/REDIS_MASTER_IP" "127.0.0.1"
  - consul kv put "development/REDIS_MASTER_PASSWORD" ""
  - consul kv put "development/LISTENER_COUNT" "1"
  - sudo vault kv put secret/development/REDIS_MASTER_PASSWORD value=""
  - sudo vault status
  - bash scripts/travis_run_go_app.sh
