language: go

addons:
  apt:
    packages:
      - redis-server
      - lynx

go:
  - "1.10"

before_script:
  - bash ./var.env

env:
  - REDIS_MASTER_IP=0.0.0.0 REDIS_HOST_PORT=6379 REDIS_MASTER_PASSWORD=""
script:
      - bash scripts/travis_run_Go_app.sh