language: go

addons:
  apt:
    packages:
      - redis-server
      - lynx

go:
  - "1.10"
      
before_script:
  - pushd packer
  - if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
  - popd
       
script:
  - source ./var.env
  - export REDIS_MASTER_IP=0.0.0.0
  - export REDIS_MASTER_PASSWORD=""
  - bash scripts/travis_run_go_app.sh
